---
- name: Pop OS desktop setup
  hosts: localhost
  become: true
  connection: local
  pre_tasks:
    - name: update package cache
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install prerequisites
      package:
        name:
          - python3-psutil

  tasks:
    # - include: tasks/flatpaks.yml
    - include: tasks/packages.yml
    # - include: tasks/extensions.yml
    - include: tasks/gnome.yml
    - include: tasks/fonts.yml
    - include: tasks/git.yml
    - include: tasks/wezterm.yml
