---
- name: Pop OS desktop setup
  hosts: localhost
  connection: local
  pre_tasks:
    - name: update package cache
      become: true
      apt: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install prerequisites
      become: true
      package:
        name:
          - python3-psutil

  tasks:
    # - include: tasks/flatpaks.yml
    - include: tasks/packages.yml
    - include: tasks/lsd.yml
    - include: tasks/dust.yml
    # - include: tasks/extensions.yml
    - include: tasks/gnome.yml
    - include: tasks/fonts.yml
    - include: tasks/neovim.yml
    - include: tasks/git.yml
    - include: tasks/wezterm.yml
    - include: tasks/zsh.yml
    - include: tasks/python.yml
