- name: Ensure fonts directory exists
  file:
    path: "/home/david/.fonts"
    state: directory
    owner: david
    group: david
    mode: 0775

- name: Jet Brains exists
  shell: "ls /home/david/.fonts/Jet*Brains*Mono*"
  register: jetbrains_exists
  ignore_errors: true
  changed_when: false

- name: Download Jet Brains
  when: jetbrains_exists is failed
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/JetBrainsMono.zip"
    dest: "/home/david/.fonts/"
    remote_src: true

- name: Refresh font list
  ansible.builtin.command: fc-cache -fv
  changed_when: false
