# git repositories to clone
- name: Dotfiles
  become_user: david
  git:
    repo: https://github.com/DavidRambo/dotfiles.git
    dest: "/home/david/repos/dotfiles/"
    bare: true
    version: main

# - name: Delete .bashrc
#   file:
#     path: "/home/david/.bashrc"
#     state: absent

# - name: Delete .vimrc
#   file:
#     path: "/home/david/.vimrc"
#     state: absent
 
# - name: Checkout dotfiles
#   command:
#     chdir="/home/david/repos/dotfiles/"
#   command:
#     cmd: git checkout

- name: PowerLevel10k for zsh
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "/home/david/powerlevel10k/"
    clone: true
    depth: 1
    version: HEAD
