# Keybindings
- name: move window up a workspace
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-up"
    value: "['<Primary><Shift><Super>u']"
    state: present

- name: move window down a workspace
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-down"
    value: "['<Primary><Shift><Super>e']"
    state: present

- name: move window left a workspace
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
    value: "['<Primary><Shift><Super>n']"
    state: present

- name: move window right a workspace
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
    value: "['<Primary><Shift><Super>i']"
    state: present

- name: Switch to left workspace
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left"
    value: "['<Primary><Super>n']"
    state: present

- name: Switch to right workspace
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right"
    value: "['<Primary><Super>i']"
    state: present

- name: Switch to workspace 1
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1"
    value: "['<Primary><Super>1']"
    state: present

- name: Switch to workspace 2
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2"
    value: "['<Primary><Super>2']"
    state: present

- name: Switch to workspace 3
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3"
    value: "['<Primary><Super>3']"
    state: present

- name: Switch to workspace 4
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4"
    value: "['<Primary><Super>4']"
    state: present

- name: Switch applications
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-applications"
    value: "['<Alt>Tab']"
    state: present

- name: Switch applications backwards
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
    value: "['<Shift><Alt>Tab']"
    state: present

- name: Toggle fullscreen
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/toggle-fullscreen"
    value: "['<Super>m']"
    state: present

# Launchers
- name: Launch calculator
  dconf:
    key: "org/gnome/settings-daemon/plugins/media-keys/calculator"
    value: "['<Super>c']"
    state: present

- name: Launch Home Folder in File Explorer
  dconf:
    key: "org/gnome/settings-daemon/plugins/media-keys/home"
    value: "['<Super>h']"
    state: present

# Window Manager Preferences
- name: Focus Mode
  dconf:
    key: "org/gnome/desktop/wm/preferences/focus-mode"
    value: "click"
    state: present

- name: Hide Applications button
  dconf:
    key: "org/gnome/shell/extensions/pop-cosmic/show-applications-button"
    value: "false"
    state: present

- name: Hide Workspaces button
  dconf:
    key: "org/gnome/shell/extensions/pop-cosmic/show-workspaces-button"
    value: "false"
    state: present

# Pop-Shell
- name: Pop-Shell Settings
  dconf:
    key: "org/gnome/shell/extensions/pop-shell/{{ pop_shell_dict.key }}"
    value: "{{ pop_shell_dict.value }}"
    state: present
    vars:
      pop_shell_dict:
        show-title: false
        gap-inner: "uint32 3"
        gap-outer: "uint32 3"
        active-hint: true
        active-hint-border-radius: "uint32 2"
        hint-color-rgba: "rgb(110,115,141)"
        focus-down: "['<Super>Down', '<Super>KP_Down', '<Super>e']"
        focus-left: "['<Super>Left', '<Super>KP_Left', '<Super>n']"
        focus-right: "['<Super>Right', '<Super>KP_Right', '<Super>i']"
        focus-up: "['<Super>Up', '<Super>KP_Up', '<Super>u']"

# Gnome Terminal Profile
- name: Gnome Terminal Profile - Catppuccin Macchiato
  dconf:
  key: "org/gnome/terminal/legacy/profiles:/:5083e06b-024e-46be-9cd2-892b814f1fc8/{{ gnome_term_dict.key }}"
  value: "{{ gnome_term_dict.value }}"
  state: present
  vars:
    gnome_term_dict:
      background-color: "#24273a"
      cell-height-scale: 1.2000000000000002
      cursor-background-color: "#f4dbd6"
      cursor-colors-set: true
      cursor-foreground-color: "#24273a"
      font: "JetBrains Mono 12"
      foreground-color: "#cad3f5"
      highlight-background-color: "#24273a"
      highlight-colors-set: true
      highlight-foreground-color: "#5b6078"
      palette: ['#494d64', '#ed8796', '#a6da95', '#eed49f', '#8aadf4', '#f5bde6', '#8bd5ca', '#b8c0e0', '#5b6078', '#ed8796', '#a6da95', '#eed49f', '#8aadf4', '#f5bde6', '#8bd5ca', '#a5adcb']
      use-theme-colors: false
      visible-name: "Catppuccin Macchiato"

# File Manager
- name: List-view as default in file explorer
  dconf:
    key: "org/gnome/nautilus/preferences/default-folder-viewer"
    value: "list-view"
    state: present

- name: Filter by last modified
  dconf:
    key: "org/gnome/nautilus/preferences/search-filter-time-type"
    value: "last_modified"
    state: present

- name: List-view when searching
  dconf:
    key: "org/gnome/nautilus/preferences/search-view"
    value: "list-view"
    state: present

# Mouse
- name: Flat mouse acceleration
  dconf:
    key: "org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "flat"
    state: present

- name: Mouse speed
  dconf:
    key: "org/gnome/desktop/peripherals/mouse/speed"
    value: "-0.125"
    state: present

# Extension Settings
- name: Horizontal workspace indicator
  dconf:
    key: "org/gnome/shell/extensions/horizontal-workspace-indicator/widget-orientation"
    value: "horizontal"
    state: present

- name: Workspace indicator on left
  dconf:
    key: "org/gnome/shell/extensions/horizontal-workspace-indicator/widget-position"
    value: "left"
    state: present
