# Install neovim nightly
- name: Download latest neovim
  get_url:
    url="https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb"
    dest="/home/{{ ansible_env.USER }}/Downloads/nvim-linux64.deb"

- name: Install neovim deb
  apt: deb="/home/{{ ansible_env.USER }}/Downloads/nvim-linux64.deb"
  sudo: true
